### PR TITLE
Update launcher icons

### PR DESCRIPTION
**Pull request by naveensingh**

### CODE REVIEW

**Comment by David-Else** [comment]
I just updated from the old SMT calendar to the Fossify calendar on fdroid and my icon is still orange. File Manager and Gallery are green. It is version `1.0.2`. Thanks for the amazing work!

**Comment by naveensingh** [comment]
@David-Else Hi!

> I just updated from the old SMT calendar to the Fossify calendar

It's not possible to 'update' from SMT to Fossify so I assume you uninstalled the SMT version and then installed the Fossify version? Are you using Simple Thank You by any chance?

Please attach a screenshot of the app icon color dialog. Here's how:
 - Launch Fossify Calendar
 -  Go to settings -> Customize Colors -> App icon color
 - A dialog should appear with the current icon selected by default.
 - Upload screenshot

Thanks

**Comment by David-Else** [comment]
Yes, I uninstalled the SMT version and then installed the Fossify version.

Here are the screenshots:
fossify-cal2

## and clicking on the `App icon color` button
fossify-cal1

**Comment by naveensingh** [comment]
I double-checked and Fossify Calendar uses green icon by default.

It appears you are using a custom theme, maybe you customized the app icon color as well thinking it was accent/primary color? As visible in your first screenshot, the app icon color can be customized on the theme page too as long as you are using a static theme.

If it's not too much work, please try to uninstall and reinstall Fossify Calendar and if it still uses the orange icon by default, file a bug report.

**Comment by David-Else** [comment]
I found the problem by reinstalling and paying more attention. I saved my settings in SMT, and then when I reload them into Fossify Calendar the icon goes orange. Not sure if this intended behaviour as I never touched the icon color in SMT, but it makes sense. Thanks for your help!

**Comment by naveensingh** [comment]
> Not sure if this intended behaviour as I never touched the icon color in SMT

Yeah, as of now, this is the intended behavior.

**Pull request merged**
