### PR TITLE
long click->new Event on day in month view

### LINKED ISSUE #182: Long press on Day in Month view for new appointment
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Calendar/issues) or [closed](https://github.com/FossifyOrg/Calendar/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Calendar/discussions) or [closed](https://github.com/FossifyOrg/Calendar/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Currently the app will switch to day view even when you long press but it should open the new entry popup that is shown in the week view to quickly preset the wanted day.

### Why do you want this feature?

It saves some time and makes it easier to relate new appointments to other appointments.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gitmacer**
#### What is it?
- [ ] Bugfix
- [X] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

- Long press on day will open new appointment UI

I choosed to open the event UI instead of the task/event selection popup because of the improved workflow. That is the mostly wanted option and you can still use the + button to add tasks. (being able to choose even/popup in the settings could be useful)

#### Before/After Screenshots/Screen Record

- After:
[Screen_recording_20240321_210749.webm](https://github.com/FossifyOrg/Calendar/assets/37345589/88042238-ca6c-403a-891f-a36c6d967019)

#### Fixes the following issue(s)

- Fixes #182

#### Acknowledgement
- [X] I read the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Aga-C** [comment]
It should work the same as adding events in weekly view - it should display a popup for choosing between events and task if `Allow creating tasks` is enabled in Settings.

**Comment by gitmacer** [comment]
> It should work the same as adding events in weekly view - it should display a popup for choosing between events and task if `Allow creating tasks` is enabled in Settings.

ok I will look into it.

**Comment by gitmacer** [comment]
@Aga-C can you take another look and test it? 
I think we should implement custom longclick logic to make sure it dosn't get triggered by accident when touching but scolling after some time. 
default OnLongClick:
trigger after 500ms without scrolling within the time

What I suggest: 
Trigger after releasing after atleast 500ms without scrolling in the mean time.
(vibrate after 500ms to indecate longclick got registered)

what do you think about that?

**Comment by Aga-C** [comment]
> I think we should implement custom longclick logic to make sure it dosn't get triggered by accident when touching but scolling after some time.

Can you actually do this when normally using the app? When I scroll horizontally, it never happened to me. Just when I did it very slow, that I barely moved a finger, it triggered the new event popup. It looks like when the next view even barely appears on the screen, the long press event is cancelled.

However, I see two another minor problems:
- There's an animation while opening a popup. It comes visibly from the bottom when in weekly view it just appears in place. In my opinion, behavior between two views should be consistent.
- If you have event type filtered out in a quick filters list on the bottom, after closing the popup (without selecting anything) these disabled event types quickly blink.

**Comment by gitmacer** [comment]
@Aga-C should be fixed now.

I am just a little bit concerned that especially older people will accidently triggering it demo:
https://youtube.com/shorts/zFefjXy_qsA

But after creating it I admit it feels a little bit unusual. Maybe a simple option to disable it is even better. Others opinions wanted.
https://github.com/gitmacer/Calendar/tree/LongClickReleaseForNew

**Comment by Aga-C** [comment]
For now, let's leave it as it is. We'll think about it.

**Comment by gitmacer** [comment]
> For now, let's leave it as it is. We'll think about it.

That means you will merge with long press auto popup? 
Or you will think about the options and decide soon? (longer longpress time, longpress on release or option to Enable/Disable)?

**Comment by Aga-C** [comment]
I can't merge, but until Naveen will have time to check the PR, maybe we will get to some conclusion how to approach it.

**Comment by gitmacer** [comment]
> I can't merge, but until Naveen will have time to check the PR, maybe we will get to some conclusion how to approach it.

ok sounds good. Btw can you also check #181

**Comment by naveensingh** [comment]
Merging for now, we'll increase the long press timeout after someone reports this feature as a bug :)

**Comment by gitmacer** [comment]
> Merging for now, we'll increase the long press timeout after someone reports this feature as a bug :)

I noticed that is actually a device and setting depending delay so. 
My phone had it on pretty low by default.
If it is a problem we could tell them to change that setting.

**Pull request merged**
