### PR TITLE
Fix google pixel month view

### LINKED ISSUE #7: Touch is broken for Pixel 8 Pro
As described here: https://github.com/SimpleMobileTools/Simple-Calendar/issues/2277

Multiple other users reported the same issue.

### PR DESCRIPTION
**Pull request by jonas-w**
#### What is it?
- [x] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

- The problem was that the screen width is exactly divisible by 7 (the number of days in one row/week), so in line 77 (where it was `<` instead of `<=`) it instead wrapped the last element always to the next line.
https://github.com/FossifyOrg/Calendar/blob/abd573cc43dacb5320eb09a35ae94ffad821b237/app/src/main/kotlin/org/fossify/calendar/views/MonthViewWrapper.kt#L77
- Removed redundant position calculations, as they are instantly altered by the onLayout function, so they are not even used. (can be reverted if not wanted, as these changes don't affect the bug fix)

#### Before/After Screenshots/Screen Record

- Before:
As you can see the dates on the right don't have this bounding box which is clickable, and the boxes also went out of the visible area at the bottom.
image

- After:
Now every date has a bounding box that is clickable and no boxes are below the visible area.
image

#### Fixes the following issue(s)

- Fixes #7

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Calendar/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by naveensingh** [comment]
Hey, thanks for the bug fix. I'll check it soon.

**Comment by topcaser** [comment]
Perfect and thanks a lot that a fix is available since this problem bothered me already in SMT and forced me to switch to Etar. When are you going to check the commit?

**Comment by naveensingh** [comment]
Not enough fuel and too much spacetime. I'm looking at it now...

**Comment by naveensingh** [comment]
The logic sounds solid and works fine on the devices I tested. @jonas-w Good work and thanks!

This probably also happened on rare devices with non-standard display widths like 1050, 1176, 1260, etc. but those are more [common in iPhones](https://en.wikipedia.org/wiki/Comparison_of_high-definition_smartphone_displays#1125-1344_nonstandard). Google is copying everything now.

**Comment by naveensingh** [comment]
@jonas-w today is the day.

**Comment by naveensingh** [comment]
@jonas-w https://github.com/FossifyOrg/Calendar/releases/tag/1.0.3

**Pull request merged**
